language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t nherzog2020/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true nherzog2020/react-test npm test

after_success:
    - docker build -t nherzog2020/multi-client ./client
    - docker build -t nherzog2020/multi-nginx ./nginx
    - docker build -t nherzog2020/multi-server ./server
    - docker build -t nherzog2020/multi-worker ./worker
# Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
    - docker push nherzog2020/multi-client
    - docker push nherzog2020/multi-nginx
    - docker push nherzog2020/multi-server
    - docker push nherzog2020/multi-worker